# $FreeBSD$

PORTNAME=	c3
PORTVERSION=	0.6
CATEGORIES=	science
MASTER_SITES=	http://www.pozsarzs.hu/sources/

MAINTAINER=	pozsarzs@gmail.com
COMMENT=	Colour code decoder

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)

