.TH Electrontubes 1 "Electrontube bias calculator" "Pozsar Zsolt" "Electrontube bias calculator"
.SH NAME
Electrontubes \- Electrontube bias calculator application
.SH SYNOPSIS
.B electrontubes [-h | --help | -o | -offline | -v | --version]
.SH DESCRIPTION
This software  is  a electrontube bias calculator application.
  OS support: Linux and Windows.
.PP
Language support: English and Hungarian.
.TE
.SH OPTIONS
.TP
.B \-h \-\-help
Write useable parameters to console.
.TP
.B \-o \-\-offline
Switch to off-line operation mode.
.TP
.B \-v \-\-version
Write version number to console.
.SH DIRECTORIES
By default, Electrontubes is installed in
.B /opt/CheapApps/electrontubes,
but you can install it into any other directory you might prefer.
.PP
The following subdirectories are located below this directory:
.TS
tab (@);
l l.
\fBdocuments\fR@Documentation in raw text format
\fBfigures\fR@Figures in PNG format
\fBhelp\fR@Help files in HTML format
\fBmanual\fR@Manual pages
\fBlanguages\fR@Message files
.TE
.PP
My CheapApps directory:
.TS
tab (@);
l l.
\fB~/CheapApps/\fR@Directory for saved initial values (*.cav) and report files (*.txt).
\fB~/CheapApps/Reg_key\fR@Copy here your registration key (electrontubes.key)!
.TE
.SH HELP SYSTEM
Online help information is provided as a set of HTML text files.
.PP
Power supplies uses external application (web browser) to display help.
.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B >0
An error has occurred.
.SH FILES
.TP
.B ~/.CheapApps/electrontubes.ini
User specific parameters are stored in this file under the user's home directory.
.SH VERSION
This applications version is 0.3.1
.SH AUTHOR
.B Electrontubes
is produced by Pozsar Zsolt.
.TS
tab (#);
l l.
\fBHomepage:\fR#http://www.cheapapps-series.info
\fBE-mail:\fR#pozsarzs\@gmail.com
.TE
.TP
Copyright (c) 2012 Pozsar Zsolt
