#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/c3 -a -d /usr/share/doc/c3 ]; then
    ln -sf /usr/share/doc/c3 /usr/doc/c3
  fi
fi
if [ -x update-menus ]; then
  update-menus
fi
# End automatically added section
